import "./styles/index.css";

import { Inter } from "next/font/google";
import LayoutRoot from "./Layouts/page";
import type { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Comment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutRoot>{children}</LayoutRoot>
      </body>
    </html>
  );
}
